<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FactoryMind.Application\FactoryMind.Application.csproj" />
    <ProjectReference Include="..\FactoryMind.Infrastructure\FactoryMind.Infrastructure.csproj" />
    <ProjectReference Include="..\FactoryMind.Shared\FactoryMind.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
